# name of simulation run, dumps will be under this folder
sim_name: dev

# path of the directory the nodes will be saved under the simulation name
# don't leave '/' at the end
results_directory: tmp/zelig/results

# simulation events logging level
#   CRITICAL: disable any output
#   WARNING:  only simulator messages (recommended)
#   SUCCESS:  + block generations
#   INFO:     + block receipts
#   DEBUG:    + all protocol messages
log_level: INFO

# how many times to repeat the same simulation
sim_reps: 1

# number of simulation steps
sim_iters: 20000

# real-time seconds per simulation step
iter_seconds: 0.1

# expected block interval in iters
block_int_iters: 6000

# block reward gained from mining
block_reward: 100

# adjust the mining difficulty dynamically (True or False)
dynamic_difficulty: False

# maximum block size in bytes
max_block_size: 1000000 # 1 MB

# Transaction modeling detail
# Full:   transactions are propagated over the network; each node has its own mempool
# Simple: nodes share mempool; no transaction propagation over the network
# None:   no transactions; blocks have tx count and size values sampled from distributions
tx_modeling: Simple

# expected number of transactions generated by a single node at each iter
tx_per_node_per_iter: 2

# outgoing connections per node
connections_per_node: 5

# number of nodes per region
# set -1 to use the real-world values provided below
nodes_in_each_region: 10

# setup nodes
#   at most one entry per region
# miner powers are represented as that region's percent share in global power
# comment out items to remove region
nodes:
  - count: 189
    region: CH
    region_mine_power: 70.74
    mining_strategy: Honest
    node_mode: Miner

  - count: 1892
    region: US
    region_mine_power: 7.87
    mining_strategy: Honest
    node_mode: Miner

  - count: 251
    region: RU
    region_mine_power: 7.50
    mining_strategy: Honest
    node_mode: Miner

  - count: 5
    region: KZ
    region_mine_power: 6.71
    mining_strategy: Honest
    node_mode: Miner

  - count: 19
    region: ML
    region_mine_power: 4.71
    mining_strategy: Honest
    node_mode: Miner

  - count: 316
    region: CN
    region_mine_power: 0.89
    mining_strategy: Honest
    node_mode: Miner

  - count: 1769
    region: GE
    region_mine_power: 0.61
    mining_strategy: Honest
    node_mode: Miner

  - count: 32
    region: NR
    region_mine_power: 0.52
    mining_strategy: Honest
    node_mode: Miner

  # - count: 2
  #   region: VN
  #   region_mine_power: 0.46
  #   mining_strategy: Selfish
  #   node_mode: EclipseAttacker